version: '2'
services:
  mongo:
    image: mongo:3.0
    ports:
      - '27017:27017'
    volumes_from:
      - mongodata

  mongodata:
    image: tianon/true
    volumes:
      - /data/db

  generics-express-api:
    build: .
    command: node_modules/.bin/nodemon --exec npm run serve
    environment:
      NODE_ENV: development
      DEBUG: 'generics-express-api'
      VIRTUAL_HOST: 0.0.0.0
      VIRTUAL_PORT: 3001
      AUTH_PASSWORD: 58SyM;lYnE/B1xd7rjKJ2]7.543&UWnv
      JWT_KEY: vZiYpmTzqXMp8PpYXKwqc9ShQ1UhyAfy
    ports:
      - '3001:3001'
    volumes:
      - ./:/home/app/library
      - /home/app/library/node_modules
    links:
     - mongo

  mongo-test:
    image: mongo:3.0
    ports:
      - '27017:27017'

  generics-express-api-test:
    build: .
    command: gulp test
    environment:
      NODE_ENV: test
      DEBUG: 'generics-express-api-test'
      VIRTUAL_HOST: 0.0.0.0
      VIRTUAL_PORT: 3002
      AUTH_PASSWORD: 58SyM;lYnE/B1xd7rjKJ2]7.543&UWnv
      JWT_KEY: vZiYpmTzqXMp8PpYXKwqc9ShQ1UhyAfy
    ports:
      - '3002:3002'
    volumes:
      - ./:/home/app/library
      - /home/app/library/node_modules
    links:
     - mongo-test

